### ISSUE TITLE
[testing] Expand tests to cover unpickleable stuff?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pympipool#117]
I would be interested in adding explicit verification that `pympipool.Executor` can handle un-pickle-able stuff. I have a test suite already [here](https://github.com/pyiron/pyiron_contrib/blob/main/tests/unit/executors/test_cloudprocesspool.py) that (almost!) works out-of-the box when you plug in `pympipool.Executor`, so the simplest thing would be to shove those into the executor tests. However, maybe there is a more generic place to do this sort of thing like in the sockets where the cloudpickling is happening?

(The "almost" is just to do with how things get handled when an exception is raised, which is test for a spec I wrote over in contrib and doesn't need to be how we do it. I am also struggling that pycharm fails to shutdown the processes and finish the tests, so it's possible that this issue goes away entirely once PyCharm plays nicely with Executor.)

**Comment by jan-janssen** [comment]
> However, maybe there is a more generic place to do this sort of thing like in the sockets where the cloudpickling is happening?

The communication interface is defined in https://github.com/pyiron/pympipool/blob/main/pympipool/external_interfaces/communication.py and this is already what we use inside `pympipool` as well as `pylammpsmpi`. 

> (The "almost" is just to do with how things get handled when an exception is raised, which is test for a spec I wrote over in contrib and doesn't need to be how we do it.

I am happy to add the Exception, when it increases the compatibility with the standard process pool. Can you point me to the corresponding test? Is it this one ? 
```
    def test_exception(self):
        @dynamic_foo()
        def raise_error():
            raise RuntimeError

        re = raise_error()
        executor = CloudpickleProcessPoolExecutor()
        fs = executor.submit(re.run)
        with self.assertRaises(RuntimeError):
            fs.result()
```

> I am also struggling that pycharm fails to shutdown the processes and finish the tests, so it's possible that this issue goes away entirely once PyCharm plays nicely with Executor.)

I also have issues with PyCharm on Mac OS X, I thought it might be related to security settings but I have not spend the time to analyse it in more detail as the continuous integration works just fine.

**Comment by liamhuber** [comment]
> > However, maybe there is a more generic place to do this sort of thing like in the sockets where the cloudpickling is happening?
> 
> The communication interface is defined in https://github.com/pyiron/pympipool/blob/main/pympipool/external_interfaces/communication.py and this is already what we use inside `pympipool` as well as `pylammpsmpi`.

Ok, I could see the tests over in contrib either being adapted to work as tests on `SocketInterface.send(receive)_dict`, or as something closer to an integration tests in exactly(?) their current form being used with `Executor.submit`. Both approaches seem reasonable to me.

> I am happy to add the Exception, when it increases the compatibility with the standard process pool. Can you point me to the corresponding test? Is it this one ?
> 
> ```
>     def test_exception(self):
>         @dynamic_foo()
>         def raise_error():
>             raise RuntimeError
> 
>         re = raise_error()
>         executor = CloudpickleProcessPoolExecutor()
>         fs = executor.submit(re.run)
>         with self.assertRaises(RuntimeError):
>             fs.result()
> ```
> 
>  > I am also struggling that pycharm fails to shutdown the processes and finish the tests, so it's possible that this issue goes away entirely once PyCharm plays nicely with Executor.)
> 
> I also have issues with PyCharm on Mac OS X, I thought it might be related to security settings but I have not spend the time to analyse it in more detail as the continuous integration works just fine.

Yes, it is exactly that one. My current suspicion is that `pympipool.Executor` _does_ fulfill this test already, and it's only the never-ending-test side-effect from running the tests with PyCharm is causing the trouble. Let's run the exception test on the CI to check before we worry about making any modifications to the code.

It's reassuring that I'm not the only one with PyCharm+pympipool test trouble, but it is also a pain. I agree it's low-priority as long as the CI is working. However, maybe it's good at the end of the day that I made the much simpler `CloudpickleProcessPoolExecutor`; I run the unit tests multiple times/day when I'm working on the workflow stuff, so it's super nice to have an executor around that can be used to test the asychronous processing in workflows right on my local machine.

So what I'd like to do is expose `pympipool.Executor` on the `Workflow.create` menu and use it as the "recommended" executor, but still allow `pyiron_contrib.executors. CloudpickleProcessPoolExecutor` to stick around (at least until the PyCharm issue gets resolved).

**Comment by jan-janssen** [comment]
@liamhuber Can you test the exceptions again with the new version `0.5.5`? It should be fixed now.

**Comment by liamhuber** [comment]
@jan-janssen, I'm afraid it just hangs now, also in the notebook. In fact, poking around I discovered that it hangs under even very simple conditions.

Modified test:
```python
from functools import partialmethod
import unittest

# from pyiron_contrib.executors.cloudpickleprocesspool import (
#     CloudpickleProcessPoolExecutor
# )
from pympipool import Executor


class CloudpickleProcessPoolExecutor(Executor):
    def __init__(self, *args, **kwargs):
        super().__init__(1, *args, **kwargs)

class TestCloudpickleProcessPoolExecutor(unittest.TestCase):
    def test_exception(self):
        @dynamic_foo()
        def raise_error():
            raise RuntimeError

        re = raise_error()
        executor = CloudpickleProcessPoolExecutor()
        fs = executor.submit(re.run)
        with self.assertRaises(RuntimeError):
            fs.result()
```

Simpler test that is even hanging in my notebook:

```python
import pympipool

def raise_error():
    raise RuntimeError

executor = pympipool.Executor(1)
fs = executor.submit(raise_error)
fs.result()
```

I was concerned that this wasn't in your tests, so I took a peek at #118 and see that you _do_ test this! However, it looks like there is a bug in the process of returning a future. I.e.

This runs fine and raises the expected error:
```python
import pympipool

def raise_error():
    raise RuntimeError
    
with pympipool.Executor(1) as executor:
    executor.submit(raise_error)
```

This executes fine without an error (IMO that's the desired behaviour):
```python
import pympipool

def raise_error():
    raise RuntimeError

executor = pympipool.Executor(1)
fs = executor.submit(raise_error)
```

_However_, as soon as you call `fs.result()` after the above snippet, it hangs forever instead of returning the error. 

I don't think it's an intentional restriction that the executor always needs to be used in the scope of a `with` clause, so I guess [the test](https://github.com/pyiron/pympipool/blob/316357b460c2827130d87c610a1f1e3c841fcb52/tests/test_worker.py#L60) should be expanded to cover both the `with` case and the case of assigning the executor to a normally-scoped varaible.

**Comment by liamhuber** [comment]
I pushed a little deeper -- it really is exactly `Future.result()` that is killing us. I wanted to make sure that it wasn't the interactive interpreter causing trouble so I put the following snippets in their own .py files and executed them:

```python
import pympipool

def raise_error():
    raise RuntimeError

with pympipool.Executor(1) as executor:
    fs = executor.submit(raise_error)
```

```python
import pympipool

def raise_error():
    raise RuntimeError

with pympipool.Executor(1) as executor:
    fs = executor.submit(raise_error)
    fs.result()
```

The first raises the expected error, the second hangs.

So it's not `with` vs not-`with`, it's just that in your test `.result()` is never called so the `with` clause has a chance to terminate and we see the expected error. In the second example `fs.result()` gets us into a state of permanent waiting.

**Comment by jan-janssen** [comment]
Yes, I guess currently the exception is only called on `.join()` this happens when the `with` statement is closed.

**Comment by jan-janssen** [comment]
@liamhuber Can you try https://github.com/pyiron/pympipool/pull/120 ? this solves the issue with the second example - at least on my machine.

**Comment by liamhuber** [comment]
Can #120 just add a sub test where the future result is explicitly called? I've got to leave early today and won't be able to work on this again until tomorrow, but (other than the pycharm hanging business) the failure of .result() to raise the error was the only outstanding issue so once this doesn't hang the odds are extremely good that it will work over in contrib. This behaviour should be verified at the source in any case, so I strongly recommend to add the test to the exact same PR that is patching the bug.

**Comment by jan-janssen** [comment]
> so I strongly recommend to add the test to the exact same PR that is patching the bug.

Done

**Comment by liamhuber** [comment]
If I run into trouble using this downstream I'll reopen the issue, but with that new test passing my baseline scenario is that this will work for Workflows now

**Comment by liamhuber** [comment]
Indeed, the latest release is working A-OK for functional nodes 👍

**Comment by jan-janssen** [comment]
Ok, then I leave it up to you if you want to extend the tests here or keep the new tests in pyiron_contrib.
